#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_DOOR_LOCK_DISPLAY=y

CONFIG_DISPLAY=y
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_DISPLAY_LOG_LEVEL_WRN=y

CONFIG_LVGL=y
CONFIG_LV_COLOR_DEPTH_32=y
CONFIG_LV_USE_CUSTOM_MALLOC=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_BUTTON=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_IMAGE=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_28=y

CONFIG_DISPLAY_THREAD_PRIORITY=5
CONFIG_DISPLAY_THREAD_STACK_SIZE=8192
